"""Pandera schemas for generated data-pipeline artifacts."""

import pandera.pandas as pa

WAVES = ["IFLS4", "IFLS5"]
BINARY = [0, 1]
CASH_TRANSFER_CARD_COLUMNS = [
    "cash_transfer_health_card",
    "cash_transfer_dana_sehat",
    "cash_transfer_poverty_certificate",
    "cash_transfer_blt_blsm_card",
    "cash_transfer_bsm",
    "cash_transfer_jslu",
    "cash_transfer_disability",
    "cash_transfer_child_welfare",
    "cash_transfer_troubled_youth",
    "cash_transfer_social_security_card",
    "cash_transfer_bpjs_health",
    "cash_transfer_bpjs_accident",
    "cash_transfer_bpjs_retirement",
    "cash_transfer_bpjs_life",
    "cash_transfer_family_card",
]


def _wave_column() -> pa.Column:
    return pa.Column(str, checks=pa.Check.isin(WAVES), nullable=False, coerce=True)


def _id_column() -> pa.Column:
    return pa.Column(str, nullable=False, coerce=True)


def _binary_column(*, nullable: bool = False) -> pa.Column:
    return pa.Column(
        "Int32",
        checks=pa.Check.isin(BINARY),
        nullable=nullable,
        coerce=True,
    )


def _schema_columns(
    schema: pa.DataFrameSchema, names: list[str]
) -> dict[str, pa.Column]:
    return {name: schema.columns[name] for name in names}


# Generated by code/data/01_extract_individuals.py -> data/generated/individuals.parquet
# Row level: one person-wave interview record, keyed by pidlink + wave.
INDIVIDUALS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Individual interview date built from the wave-specific cover/date fields.
        "interview_datetime": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Day value of interview date
        "day": pa.Column(
            int, checks=pa.Check.between(1, 31), nullable=False, coerce=True
        ),
        # Month value of interview date
        "month": pa.Column(
            int, checks=pa.Check.between(1, 12), nullable=False, coerce=True
        ),
        # Year value of interview date
        "year": pa.Column(
            int, checks=pa.Check.between(2007, 2015), nullable=False, coerce=True
        ),
        # Start hour
        "hour_start": pa.Column(
            int, checks=pa.Check.between(0, 23), nullable=False, coerce=True
        ),
        # End hour
        "hour_end": pa.Column(
            int, checks=pa.Check.between(0, 23), nullable=False, coerce=True
        ),
        # BPS two-digit province code from the household screening file.
        "province_code": pa.Column(int, nullable=False, coerce=True),
        # BPS four-digit kabupaten code, computed as province*100 plus within-province kabupaten.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # BPS seven-digit kecamatan code, computed from kabupaten_code and within-kabupaten kecamatan.
        "kecamatan_code": pa.Column(int, nullable=False, coerce=True),
        # BPS two-digit province code from the household screening file.
        "province_full_code": pa.Column(int, nullable=False, coerce=True),
        # BPS four-digit kabupaten code, computed as province*100 plus within-province kabupaten.
        "kabupaten_full_code": pa.Column(int, nullable=False, coerce=True),
        # BPS seven-digit kecamatan code, computed from kabupaten_code and within-kabupaten kecamatan.
        "kecamatan_full_code": pa.Column(int, nullable=False, coerce=True),
        # Combined geo code converted to 2014 BPS codes compatible with GADM boundaries; may have more than 1 code for IFLS4 due boundary changes
        "gadm_fullcode": pa.Column(
            str,
            checks=pa.Check.str_matches(r"^\d+(,\d+)*$"),
            nullable=False,
            coerce=True,
        ),
        # Description of how 2007 BPS codes were mapped to 2014 ones
        "kecamatan_code_map": pa.Column(str, nullable=False, coerce=True),
        # IFLS survey wave for the person record.
        "wave": _wave_column(),
        # Community ID
        "community_id": pa.Column(str, nullable=False, coerce=True),
    },
    strict=True,
    unique=["pidlink", "wave"],
)


# Generated by code/data/03_extract_conversions.py -> data/generated/03_currency_conversions.parquet
# Row level: one monthly USD-per-IDR conversion factor, keyed by year + month.
CURRENCY_CONVERSIONS_SCHEMA = pa.DataFrameSchema(
    {
        "year": pa.Column(
            int, checks=pa.Check.between(2007, 2015), nullable=False, coerce=True
        ),
        "month": pa.Column(
            int, checks=pa.Check.between(1, 12), nullable=False, coerce=True
        ),
        "conversion_factor": pa.Column(
            float, checks=pa.Check.gt(0), nullable=False, coerce=True
        ),
    },
    strict=True,
    unique=["year", "month"],
)


# Generated by code/data/04_community_info.py -> data/generated/04_community_info.parquet
# Row level: one community-wave record, keyed by community_id + wave.
COMMUNITY_INFO_SCHEMA = pa.DataFrameSchema(
    {
        "community_id": _id_column(),
        "wave": _wave_column(),
        "community_travel_market_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_market_cost": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_market_time": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_market_method": pa.Column(
            "Int32",
            checks=pa.Check.isin([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 95]),
            nullable=True,
            coerce=True,
        ),
        "community_travel_district_capital_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_district_capital_cost": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_district_capital_time": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_district_capital_method": pa.Column(
            "Int32",
            checks=pa.Check.isin([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 95]),
            nullable=True,
            coerce=True,
        ),
        "community_travel_provincial_capital_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_provincial_capital_cost": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_provincial_capital_time": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "community_travel_provincial_capital_method": pa.Column(
            "Int32",
            checks=pa.Check.isin([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 95]),
            nullable=True,
            coerce=True,
        ),
    },
    strict=True,
    unique=["community_id", "wave"],
)


# Generated by code/data/24_score_cesd.py -> data/generated/24_cesd_scores.parquet
# Row level: one person-wave CES-D score, keyed by pidlink + wave.
CESD_SCORES_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave that produced the mental-health record.
        "wave": _wave_column(),
        # Sum of CES-D-10 frequency scores after reverse-coding positive items.
        "cesd_raw": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # IFLS4 screener count of endorsed CES-D items; missing for IFLS5.
        "cesd10_count": pa.Column(
            float, checks=pa.Check.between(0, 10), nullable=True, coerce=True
        ),
        # Indicator for CES-D raw score at or above the cutoff of 10.
        "depressed": _binary_column(),
        # Number of CES-D items contributing to the person-wave score.
        "n_items": pa.Column(int, checks=pa.Check.eq(10), nullable=False, coerce=True),
        # CES-D factor scores and within-wave standardized versions.
        "somatic": pa.Column(
            float, checks=pa.Check.between(0, 15), nullable=False, coerce=True
        ),
        "depraffect": pa.Column(
            float,
            checks=pa.Check.between(0, 9),
            coerce=True,
            nullable=False,
        ),
        "posaffect": pa.Column(
            float,
            checks=pa.Check.between(0, 6),
            coerce=True,
            nullable=False,
        ),
        "somatic_z": pa.Column(float, nullable=False, coerce=True),
        "depraffect_z": pa.Column(
            float,
            coerce=True,
            nullable=False,
        ),
        "posaffect_z": pa.Column(
            float,
            coerce=True,
            nullable=False,
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/22_build_person_covariates.py -> data/generated/22_stressors.parquet
# Row level: one person-wave stressor/covariate record, keyed by pidlink + wave.
STRESSORS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Respondent age from the household roster after sentinel cleaning.
        "age": pa.Column(
            float, checks=pa.Check.between(0, 120), nullable=True, coerce=True
        ),
        # Respondent sex from the roster, normalized to F/M.
        "sex": pa.Column(
            str, checks=pa.Check.isin(["F", "M"]), nullable=False, coerce=True
        ),
        # Indicator for currently married marital status.
        "married": _binary_column(),
        # Indicator for widowed marital status.
        "widowed": _binary_column(),
        # Approximate years of schooling mapped from IFLS education level.
        "edu_yrs": pa.Column(
            "Int64", checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # IFLS survey wave for the stressor/covariate record.
        "wave": _wave_column(),
        # Household size used in per-capita expenditure calculations.
        "hhsize": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # Nominal monthly per-capita household expenditure.
        "pce": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # Natural log of monthly per-capita expenditure.
        "pce_log": pa.Column(float, nullable=True, coerce=True),
        # Within-wave quintile of monthly per-capita expenditure.
        "pce_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Household reported any natural disaster in the past 5 years.
        "disaster_5yr": _binary_column(),
        # Household reported a severe natural disaster in the past 5 years.
        "disaster_severe_5yr": _binary_column(),
        # Household had a loan application rejected.
        "loan_rejected": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/10_fetch_temperature_gee.py -> data/generated/daily_temperature_kab.parquet
# Row level: one GADM geography-day weather record, keyed by gadm_fullcode + date.
DAILY_TEMPERATURE_SCHEMA = pa.DataFrameSchema(
    {
        # Combined 2014-compatible GADM/BPS code identifying the reduced polygon.
        "gadm_fullcode": pa.Column(str, nullable=False, coerce=True),
        # BPS two-digit province code for regional summaries.
        "province_code": pa.Column(int, nullable=False, coerce=True),
        # Geography match level used to construct the reduced polygon.
        "match_level": pa.Column(
            str,
            checks=pa.Check.isin(["kecamatan", "kabupaten", "province"]),
            nullable=False,
            coerce=True,
        ),
        # Calendar date of the daily ERA5-Land aggregate.
        "date": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Daily polygon-mean 2m air temperature in Celsius.
        "tmean_c": pa.Column(float, nullable=False, coerce=True),
        # Daily maximum 2m air temperature in Celsius.
        "tmax_c": pa.Column(float, nullable=False, coerce=True),
        # Daily minimum 2m air temperature in Celsius.
        "tmin_c": pa.Column(float, nullable=False, coerce=True),
        # Daily polygon-mean 2m dewpoint temperature in Celsius.
        "dewp_c": pa.Column(float, nullable=False, coerce=True),
        # Daily total precipitation in millimeters.
        # TODO: for some reason, precip_mm has negative values so remove for now
        "precip_mm": pa.Column(
            float,
            nullable=False,
            coerce=True,
            # checks=pa.Check.ge(0),
        ),
        # Relative humidity percentage derived from mean temperature and dewpoint.
        "rh_pct": pa.Column(
            float,
            nullable=False,
            coerce=True,
            checks=pa.Check.between(0, 100),
        ),
        # Steadman/NWS heat index in Celsius derived from temperature and humidity.
        "heat_idx_c": pa.Column(float, nullable=False, coerce=True),
    },
    strict=True,
    unique=["gadm_fullcode", "date"],
)

# Generated by code/data/10_fetch_temperature_gee.py -> data/generated/daily_temperature_kab.parquet
# Row level: one GADM geography-day weather record with heat features, keyed by gadm_fullcode + date.
DAILY_TEMPERATURE_HEAT_SCHEMA = pa.DataFrameSchema(
    {
        # Base daily weather columns from DAILY_TEMPERATURE_SCHEMA.
        **DAILY_TEMPERATURE_SCHEMA.columns,
        # Indicator that daily maximum temperature is at least 28 C.
        "hot28": _binary_column(),
        # Indicator that daily maximum temperature is at least 30 C.
        "hot30": _binary_column(),
        # Indicator that daily maximum temperature is at least 32 C.
        "hot32": _binary_column(),
        # Count of hot28 days in the current and previous 6 days.
        "hot28_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot28 days in the current and previous 29 days.
        "hot28_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Count of hot30 days in the current and previous 6 days.
        "hot30_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot30 days in the current and previous 29 days.
        "hot30_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Count of hot32 days in the current and previous 6 days.
        "hot32_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot32 days in the current and previous 29 days.
        "hot32_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Cooling degree days using 22 C as the base temperature.
        "cdd": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Seven-day rolling sum of cooling degree days.
        "cdd_7d": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Rolling 30-day kabupaten-specific 90th percentile of mean temperature.
        "tmean_p90_30d": pa.Column(float, nullable=True, coerce=True),
        # Indicator that mean temperature is at least the kabupaten p90 over the pulled window.
        "is_extreme": _binary_column(),
    },
    strict=True,
    unique=["gadm_fullcode", "date"],
)

# Generated by code/data/09_fetch_merra_pm25.py -> data/generated/pm25_daily_kab.parquet
# Row level: one GADM geography-day PM2.5 record, keyed by gadm_fullcode + date.
PM25_DAILY_SCHEMA = pa.DataFrameSchema(
    {
        # Combined 2014-compatible GADM/BPS code identifying the reduced polygon.
        "gadm_fullcode": pa.Column(str, nullable=False, coerce=True),
        # BPS two-digit province code for regional summaries.
        "province_code": pa.Column(int, nullable=False, coerce=True),
        # Geography match level used to construct the reduced polygon.
        "match_level": pa.Column(
            str,
            checks=pa.Check.isin(["kecamatan", "kabupaten", "province"]),
            nullable=False,
            coerce=True,
        ),
        # Calendar date of the daily MERRA-2 aerosol aggregate.
        "date": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Estimated PM2.5 concentration in micrograms per cubic meter.
        "pm25_ugm3": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # MERRA-2 black-carbon surface aerosol mass mixing ratio component.
        "BCSMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 organic-carbon surface aerosol mass mixing ratio component.
        "OCSMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 sulfate surface aerosol mass mixing ratio component.
        "SO4SMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 fine dust surface aerosol mass mixing ratio component.
        "DUSMASS25": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # MERRA-2 fine sea-salt surface aerosol mass mixing ratio component.
        "SSSMASS25": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
    },
    strict=True,
    unique=["gadm_fullcode", "date"],
)

# Generated by code/data/20_build_economic_exposures.py -> data/generated/20_economic_exposures.parquet
# Row level: one person-wave economic exposure record, keyed by pidlink + wave.
ECONOMIC_EXPOSURES_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the economic exposure record.
        "wave": _wave_column(),
        # Respondent reports no paid work in the past week by TK01A.
        "unemployed_since_then": _binary_column(),
        # Respondent had at least one job termination in the past 5 years.
        "lost_job_5y": _binary_column(),
        # Past-5-year job termination among respondents not currently working.
        "job_loss_5y": _binary_column(),
        # Last job termination reason was fired, laid off, or plant closure.
        "job_loss_involuntary": _binary_column(),
        # Job lost due to family reasons such as marriage, childbirth, or other family matters.
        "job_loss_family": _binary_column(),
        # Past-5-year job termination with an involuntary reason.
        "involuntary_loss_5y": _binary_column(),
        # Days between interview date and the last reported job termination date.
        "days_since_last_loss": pa.Column(float, nullable=True, coerce=True),
        # Last job termination occurred within the named day window before interview.
        "lost_job_90d": _binary_column(),
        "lost_job_180d": _binary_column(),
        "lost_job_270d": _binary_column(),
        # Last job termination occurred within 365 days before interview.
        "lost_job_1_yr": _binary_column(),
        "lost_job_365d": _binary_column(),
        "lost_job_540d": _binary_column(),
        "lost_job_730d": _binary_column(),
        "lost_job_1095d": _binary_column(),
        "lost_job_1825d": _binary_column(),
        # Last job termination occurred within 6 months before interview.
        "lost_job_6_months": _binary_column(),
        # Last job termination occurred within 3 months before interview.
        "lost_job_3_months": _binary_column(),
        # Last job termination window, filtered to respondents not currently working.
        "job_loss_90d": _binary_column(),
        "job_loss_180d": _binary_column(),
        "job_loss_270d": _binary_column(),
        # Last job termination within 365 days, filtered to non-current workers.
        "job_loss_1_yr": _binary_column(),
        "job_loss_365d": _binary_column(),
        "job_loss_540d": _binary_column(),
        "job_loss_730d": _binary_column(),
        "job_loss_1095d": _binary_column(),
        "job_loss_1825d": _binary_column(),
        # Last job termination within 6 months, filtered to non-current workers.
        "job_loss_6_months": _binary_column(),
        # Last job termination within 3 months, filtered to non-current workers.
        "job_loss_3_months": _binary_column(),
        # Most recent job-loss reason code, from TK46m.
        "job_loss_reason_code": pa.Column(float, nullable=True, coerce=True),
        # Sector code for the last reported quit/fired job, from TK46G.
        "job_loss_sector": pa.Column(
            float, checks=pa.Check.between(1, 95), nullable=True, coerce=True
        ),
        # One-year job-loss subtypes based on TK46m.
        "involuntary_loss_1_yr": _binary_column(),
        "family_loss_1_yr": _binary_column(),
        # Current or primary job sector code from TK19AB.
        "current_job_sector": pa.Column(
            float, checks=pa.Check.between(1, 99), nullable=True, coerce=True
        ),
        # Current job is in agriculture/forestry/fishery; missing without current-employment records.
        "agricultural": _binary_column(nullable=True),
        # Current job is self-employed or unpaid family work; missing without current-employment records.
        "job_self_employed": _binary_column(nullable=True),
        # Any household member reports an agricultural current job.
        "farmer_hh": _binary_column(),
        # Household province is in the Sumatra/Kalimantan palm-oil region.
        "palm_region": _binary_column(),
        # World Bank monthly palm-oil price for the interview month, USD/MT.
        "palm_price_usd_mt": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Respondent is agricultural and lives in a palm-oil region.
        "palm_farmer_individual": _binary_column(),
        # Any household member is flagged as a palm farmer in that wave.
        "palm_farmer_hh": _binary_column(),
        # Household province is in a major rubber-producing region.
        "rubber_region": _binary_column(),
        # Respondent is agricultural and lives in a rubber-producing region.
        "rubber_farmer_individual": _binary_column(),
        # Household province is in a major coffee-producing region.
        "coffee_region": _binary_column(),
        # Respondent is agricultural and lives in a coffee-producing region.
        "coffee_farmer_individual": _binary_column(),
        # Household province is in a major coal-producing region.
        "coal_region": _binary_column(),
        # Respondent works in mining and lives in a coal-producing region.
        "coal_worker_individual": _binary_column(),
        # Any household member is flagged as a coal worker in that wave.
        "coal_worker_hh": _binary_column(),
        # Current individual and household monthly labor earnings.
        "job_earnings_individual": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "job_earnings_hh": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/25_build_expenditure_data.py -> data/generated/25_expenditure_data.parquet
# Row level: one person-wave expenditure record, keyed by pidlink + wave.
EXPENDITURE_DATA_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the expenditure record.
        "wave": _wave_column(),
        # Household's most valuable crop or livestock from b2_ut1/ut07a.
        "main_crop": pa.Column("Int64", nullable=True, coerce=True),
        # Monthly household non-oil food spending from KS1 weekly food items.
        "expenditure_food_items_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household cooking-oil spending from KS1 item Y.
        "expenditure_food_cooking_oil_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Total monthly household food spending from generated food components.
        "expenditure_food_total_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household non-food spending from KS2.
        "expenditure_nonfood_ks2_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household fuel spending from KS2 item A3.
        "expenditure_nonfood_fuel_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household transportation spending from KS2 item E.
        "expenditure_nonfood_transport_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # IFLS5 amount paid on the household's last vehicle-fuel purchase.
        "expenditure_nonfood_vehicle_fuel_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # IFLS5 quantity from the household's last vehicle-fuel purchase, in liters.
        "vehicle_fuel_quantity_liters": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # IFLS5 implied price per liter from the household's last vehicle-fuel purchase.
        "vehicle_fuel_price_per_litre": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household child-education spending from KS0 annual items.
        "expenditure_nonfood_children_education_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household food-gift spending from KS0 weekly food gifts.
        "expenditure_nonfood_food_gift_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Kerosene is not separately observed as monthly spending in KS4.
        "expenditure_nonfood_kerosene_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Monthly household non-food spending from KS3 annual items.
        "expenditure_nonfood_ks3_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Total monthly household non-food spending from generated non-food components.
        "expenditure_nonfood_total_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_total_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Sum of monthly household fuel and transportation spending.
        "expenditure_transport_fuel_total_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Fuel spending divided by total monthly household spending.
        "fuel_share": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        # IFLS5 last vehicle-fuel purchase divided by monthly household spending.
        "vehicle_fuel_share": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        # Transportation spending divided by total monthly household spending.
        "transport_share": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        # Fuel plus transportation spending divided by total monthly household spending.
        "fuel_transport_share": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        # Fuel spending share expressed in percentage points.
        "fuel_share_100": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "vehicle_fuel_share_100": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "transport_share_100": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "fuel_transport_share_100": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        # Full-sample z-scores of spending shares.
        "transport_share_z": pa.Column(float, nullable=True, coerce=True),
        "fuel_share_z": pa.Column(float, nullable=True, coerce=True),
        "fuel_transport_share_z": pa.Column(float, nullable=True, coerce=True),
        # Within-wave quartile/quintile codes for spending totals.
        "fuel_total_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "fuel_total_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        "transport_total_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "transport_total_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        "fuel_transport_total_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "fuel_transport_total_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Within-wave quartile/quintile codes for spending shares.
        "fuel_share_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "fuel_share_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        "transport_share_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "transport_share_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Legacy alias for within-wave quintile of transport_share.
        "transport_share_q5": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        "fuel_transport_share_quartile": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        "fuel_transport_share_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Indicator for the top within-wave quintile of transport_share.
        "high_transport_share": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Backwards-compatible name for older analysis imports.
COMMODITY_TRANSPORT_EXPOSURES_SCHEMA = EXPENDITURE_DATA_SCHEMA

# Generated by code/data/11_build_health_exposures.py -> data/generated/health_bereavement_shocks.parquet
# Row level: one person-wave health/bereavement shock record, keyed by pidlink + wave.
HEALTH_BEREAVEMENT_SHOCKS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Count of recent acute symptoms reported in the past 4 weeks.
        "n_symptoms": pa.Column(
            int, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        # Indicator for at least 5 recent acute symptoms.
        "many_symptoms": _binary_column(),
        # IFLS survey wave for the health/bereavement shock record.
        "wave": _wave_column(),
        # Respondent reported any inpatient hospitalization in the past 12 months.
        "recent_hospitalised": _binary_column(),
        # Respondent had a treated accident within 2 years before interview.
        "recent_accident_2y": _binary_column(),
        # Respondent became widowed within 5 years before interview.
        "recently_widowed_5y": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/12_build_finance_distress.py -> data/generated/finance_distress_shocks.parquet
# Row level: one person-wave financial-distress record, keyed by pidlink + wave.
FINANCE_DISTRESS_SHOCKS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the financial-distress shock record.
        "wave": _wave_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Household debt proxy; IFLS5 is loan stock, IFLS4 is recent loan flow.
        "debt": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Household is in the top quartile of positive debt within wave.
        "debt_q4": _binary_column(),
        # Respondent's summed inpatient out-of-pocket medical spending.
        "med_oop": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Respondent is in the top quartile of positive medical OOP spending within wave.
        "high_med_oop": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Core columns built inside code/data/13_build_analysis_table_input.py before adding
# model/table-specific variables.
ANALYSIS_BASE_COLUMNS = {
    **INDIVIDUALS_SCHEMA.columns,
    **_schema_columns(
        CESD_SCORES_SCHEMA,
        ["cesd_raw", "cesd10_count", "depressed", "n_items"],
    ),
    **_schema_columns(
        STRESSORS_SCHEMA,
        [
            "age",
            "sex",
            "married",
            "widowed",
            "edu_yrs",
            "hhsize",
            "pce",
            "pce_log",
            "pce_quintile",
            "disaster_5yr",
            "disaster_severe_5yr",
            "loan_rejected",
        ],
    ),
    # Final analysis sample is restricted to adults with non-missing age.
    "age": pa.Column(
        float, checks=pa.Check.between(15, 120), nullable=False, coerce=True
    ),
    **_schema_columns(
        DAILY_TEMPERATURE_HEAT_SCHEMA,
        ["tmean_c", "tmax_c", "tmin_c", "heat_idx_c", "rh_pct", "precip_mm"],
    ),
    # Geography match level used for the environmental polygon merged to the interview.
    "match_level": DAILY_TEMPERATURE_HEAT_SCHEMA.columns["match_level"],
    # Final builder clips small negative ERA5 precipitation artifacts to zero.
    "precip_mm": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
    # Mean temperature one day before interview.
    "tmean_lag1": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 3 days, excluding interview day.
    "tmean_lag3": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 7 days, excluding interview day.
    "tmean_lag7": pa.Column(float, nullable=True, coerce=True),
    # Minimum temperature one day before interview.
    "tmin_lag1": pa.Column(float, nullable=True, coerce=True),
    # Maximum temperature one day before interview.
    "tmax_lag1": pa.Column(float, nullable=True, coerce=True),
    # Heat index one day before interview.
    "heat_idx_lag1": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 30 days, excluding interview day.
    "tmean_base30": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature 7 days after interview, used as a placebo lead.
    "tmean_lead7": pa.Column(float, nullable=True, coerce=True),
    # Interview-day mean temperature minus the prior-30-day baseline.
    "t_anom_today": pa.Column(float, nullable=True, coerce=True),
    # One-day lagged mean temperature minus the prior-30-day baseline.
    "t_anom_lag1": pa.Column(float, nullable=True, coerce=True),
    # Indicator for interviews after Indonesia's 2014 fuel-subsidy reform date.
    "post_subsidy": _binary_column(),
    "post_reform": _binary_column(),
    # Indicator for interviews during the 2015 haze episode in affected months/regions.
    "haze_2015": _binary_column(),
    # IFLS4 indicator for provinces in the Yogyakarta earthquake catchment.
    "yogya_quake_catchment": _binary_column(),
    # Interview-day mean-temperature bin for non-linear heat specifications.
    "heat_bin": pa.Column(
        str,
        checks=pa.Check.isin(["<22", "22-24", "24-26", "26-28", "28+"]),
        nullable=False,
        coerce=True,
    ),
    # Interview month-year string for monthly fixed effects.
    "month_year": pa.Column(str, nullable=False, coerce=True),
    # Calendar month of interview.
    "month": pa.Column(
        int, checks=pa.Check.between(1, 12), nullable=False, coerce=True
    ),
    # Calendar year of interview.
    "year": pa.Column(
        int, checks=pa.Check.between(1900, 2100), nullable=False, coerce=True
    ),
}

# Generated by code/data/12_fetch_temperature_hourly_gee.py -> data/generated/hourly_temperature_kab.parquet
# Row level: one GADM geography-hour weather record, keyed by gadm_fullcode + datetime_utc.
HOURLY_TEMPERATURE_SCHEMA = pa.DataFrameSchema(
    {
        # Combined 2014-compatible GADM/BPS code identifying the reduced polygon.
        "gadm_fullcode": pa.Column(str, nullable=False, coerce=True),
        # BPS two-digit province code for regional summaries.
        "province_code": pa.Column(int, nullable=False, coerce=True),
        # Geography match level used to construct the reduced polygon.
        "match_level": pa.Column(
            str,
            checks=pa.Check.isin(["kecamatan", "kabupaten", "province"]),
            nullable=False,
            coerce=True,
        ),
        # UTC timestamp of the hourly ERA5-Land observation.
        "datetime_utc": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Hourly polygon-mean 2m air temperature in Celsius.
        "tmean_c_hour": pa.Column(float, nullable=False, coerce=True),
        # Hourly polygon-mean 2m dewpoint temperature in Celsius.
        "dewp_c_hour": pa.Column(float, nullable=True, coerce=True),
    },
    strict=True,
    unique=["gadm_fullcode", "datetime_utc"],
)


# Generated by code/data/26_process_temperature_data.py -> data/generated/26_processed_temperature_data.parquet
# Row level: one person-wave interview record, keyed by pidlink + wave.
PROCESSED_TEMPERATURE_SCHEMA = pa.DataFrameSchema(
    {
        "pidlink": _id_column(),
        "wave": _wave_column(),
        "match_level": pa.Column(str, nullable=True, coerce=True),
        "tmean_c": pa.Column(float, nullable=True, coerce=True),
        "tmax_c": pa.Column(float, nullable=True, coerce=True),
        "tmin_c": pa.Column(float, nullable=True, coerce=True),
        "heat_idx_c": pa.Column(float, nullable=True, coerce=True),
        "rh_pct": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "precip_mm": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "tmean_lag1": pa.Column(float, nullable=True, coerce=True),
        "tmean_lag3": pa.Column(float, nullable=True, coerce=True),
        "tmean_lag7": pa.Column(float, nullable=True, coerce=True),
        "tmin_lag1": pa.Column(float, nullable=True, coerce=True),
        "tmax_lag1": pa.Column(float, nullable=True, coerce=True),
        "heat_idx_lag1": pa.Column(float, nullable=True, coerce=True),
        "tmean_base30": pa.Column(float, nullable=True, coerce=True),
        "tmean_lead7": pa.Column(float, nullable=True, coerce=True),
        "t_anom_today": pa.Column(float, nullable=True, coerce=True),
        "t_anom_lag1": pa.Column(float, nullable=True, coerce=True),
        "heat_bin": pa.Column(
            str,
            checks=pa.Check.isin(["<22", "22-24", "24-26", "26-28", "28+"]),
            nullable=True,
            coerce=True,
        ),
        "tmean_c_dev": pa.Column(float, nullable=True, coerce=True),
        "tmax_c_dev": pa.Column(float, nullable=True, coerce=True),
        "tmin_c_dev": pa.Column(float, nullable=True, coerce=True),
        "heat_c_dev": pa.Column(float, nullable=True, coerce=True),
        "cdd_tmax30": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "cdd_tmax32": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "cdd_tmin23": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "cdd_tmin24": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "tmean_7d": pa.Column(float, nullable=True, coerce=True),
        "tmean_7d_dev": pa.Column(float, nullable=True, coerce=True),
        "tmean_30d": pa.Column(float, nullable=True, coerce=True),
        "tmean_30d_dev": pa.Column(float, nullable=True, coerce=True),
        "tmin_7d": pa.Column(float, nullable=True, coerce=True),
        "tmin_7d_dev": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_c": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_7d": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_30d": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_c_dev": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_7d_dev": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_30d_dev": pa.Column(float, nullable=True, coerce=True),
        "hot30_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "hot30_7d_dev": pa.Column(float, nullable=True, coerce=True),
        "heatwave_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "heatwave_7d_dev": pa.Column(float, nullable=True, coerce=True),
        "tmean_c_hour": pa.Column(float, nullable=True, coerce=True),
        "heat_hr_dev": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_c_hour": pa.Column(float, nullable=True, coerce=True),
        "wetbulb_hr_dev": pa.Column(float, nullable=True, coerce=True),
        "day_id": pa.Column(int, nullable=False, coerce=True),
        "tmean_c_past30_lt_21p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "tmean_c_past30_21p0_22p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "tmean_c_past30_22p5_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "tmean_c_past30_24p0_25p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "tmean_c_past30_25p5_27p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "tmean_c_past30_gt_27p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "wetbulb_c_past30_lt_19p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "wetbulb_c_past30_19p5_21p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "wetbulb_c_past30_21p0_22p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "wetbulb_c_past30_22p5_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "wetbulb_c_past30_gt_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_q1": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_q2": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_q3": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_q4": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_q5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past7_q1": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_q2": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_q3": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_q4": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_q5": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past30_d1": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d2": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d3": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d4": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d6": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d7": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d8": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d9": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past30_d10": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=True, coerce=True
        ),
        "temp_days_past7_d1": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d2": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d3": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d4": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d5": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d6": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d7": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d8": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d9": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
        "temp_days_past7_d10": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=True, coerce=True
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)


# Generated by code/data/27_asset_expenditure.py -> data/generated/27_asset_expenditure.parquet
# Row level: one person-wave household asset/expenditure record.
ASSET_EXPENDITURE_SCHEMA = pa.DataFrameSchema(
    {
        "pidlink": _id_column(),
        "wave": _wave_column(),
        "vehicle_owner": _binary_column(),
        "urban": _binary_column(),
        "urban_vehicle_hh": _binary_column(),
        "cash_transfer_recipient": _binary_column(),
        **{col: _binary_column(nullable=True) for col in CASH_TRANSFER_CARD_COLUMNS},
        "hh_nonlabor_income_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)


# Generated by code/data/28_build_sleep_duration.py -> data/generated/28_sleep_duration.parquet
# Row level: one IFLS5 person-wave record with time-use sleep duration.
SLEEP_DURATION_SCHEMA = pa.DataFrameSchema(
    {
        "pidlink": _id_column(),
        "wave": _wave_column(),
        "sleep_dur_h": pa.Column(
            float, checks=pa.Check.between(0.5, 16.0), nullable=False, coerce=True
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)


# Generated by code/data/13_build_analysis_table_input.py -> data/generated/analysis_table_input.parquet
# Row level: one canonical person-wave analysis record, keyed by pidlink + wave.
ANALYSIS_TABLE_INPUT_SCHEMA = pa.DataFrameSchema(
    {
        **ANALYSIS_BASE_COLUMNS,
        "conversion_factor": CURRENCY_CONVERSIONS_SCHEMA.columns["conversion_factor"],
        # Female indicator used by the table/regression controls.
        "female": _binary_column(),
        # CES-D total standardized within wave for pooled IFLS4/IFLS5 specifications.
        "cesd_z": pa.Column(float, nullable=False, coerce=True),
        "travel_market_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "travel_districtcapital_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "travel_provincecapital_distance": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "travel_market_distance_z": pa.Column(float, nullable=False, coerce=True),
        "travel_districtcapital_distance_z": pa.Column(
            float, nullable=False, coerce=True
        ),
        "travel_provincecapital_distance_z": pa.Column(
            float, nullable=False, coerce=True
        ),
        # Mean-centered daily temperature variables used in interaction models.
        "heat_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmean_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmax_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmin_c_dev": pa.Column(float, nullable=False, coerce=True),
        # Cooling-degree-day threshold variables used by Table 2.
        "cdd_tmax30": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmax32": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmin23": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmin24": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        # Inclusive past-week and hourly heat variables used by robustness tables.
        **_schema_columns(
            PROCESSED_TEMPERATURE_SCHEMA,
            [
                "tmean_7d",
                "tmean_7d_dev",
                "tmean_30d",
                "tmean_30d_dev",
                "tmin_7d",
                "tmin_7d_dev",
                "wetbulb_c",
                "wetbulb_7d",
                "wetbulb_30d",
                "wetbulb_c_dev",
                "wetbulb_7d_dev",
                "wetbulb_30d_dev",
                "hot30_7d",
                "hot30_7d_dev",
                "heatwave_7d",
                "heatwave_7d_dev",
                "tmean_c_hour",
                "heat_hr_dev",
                "wetbulb_c_hour",
                "wetbulb_hr_dev",
                "day_id",
                "temp_days_past30_q1",
                "temp_days_past30_q2",
                "temp_days_past30_q3",
                "temp_days_past30_q4",
                "temp_days_past30_q5",
                "temp_days_past7_q1",
                "temp_days_past7_q2",
                "temp_days_past7_q3",
                "temp_days_past7_q4",
                "temp_days_past7_q5",
                "temp_days_past30_d1",
                "temp_days_past30_d2",
                "temp_days_past30_d3",
                "temp_days_past30_d4",
                "temp_days_past30_d5",
                "temp_days_past30_d6",
                "temp_days_past30_d7",
                "temp_days_past30_d8",
                "temp_days_past30_d9",
                "temp_days_past30_d10",
                "temp_days_past7_d1",
                "temp_days_past7_d2",
                "temp_days_past7_d3",
                "temp_days_past7_d4",
                "temp_days_past7_d5",
                "temp_days_past7_d6",
                "temp_days_past7_d7",
                "temp_days_past7_d8",
                "temp_days_past7_d9",
                "temp_days_past7_d10",
            ],
        ),
        "tmean_c_past30_lt_21p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "tmean_c_past30_21p0_22p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "tmean_c_past30_22p5_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "tmean_c_past30_24p0_25p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "tmean_c_past30_25p5_27p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "tmean_c_past30_gt_27p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "wetbulb_c_past30_lt_19p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "wetbulb_c_past30_19p5_21p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "wetbulb_c_past30_21p0_22p5": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "wetbulb_c_past30_22p5_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        "wetbulb_c_past30_gt_24p0": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        **ECONOMIC_EXPOSURES_SCHEMA.columns,
        # Expenditure variables retained in the analysis table.
        **EXPENDITURE_DATA_SCHEMA.columns,
        **_schema_columns(
            ASSET_EXPENDITURE_SCHEMA,
            [
                "vehicle_owner",
                "urban",
                "urban_vehicle_hh",
                "cash_transfer_recipient",
                *CASH_TRANSFER_CARD_COLUMNS,
                "hh_nonlabor_income_mo",
            ],
        ),
        "sleep_dur_h": pa.Column(
            float, checks=pa.Check.between(0.5, 16.0), nullable=True, coerce=True
        ),
        # CES-D factor scores and within-wave standardized versions.
        **CESD_SCORES_SCHEMA.columns,
        "palm_price_gap": pa.Column(float, nullable=True, coerce=True),
        "palm_price_gap_z": pa.Column(float, nullable=True, coerce=True),
        # Wave-deflated real monetary variables generated in the final analysis table.
        "job_earnings_individual_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "job_earnings_hh_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "hh_nonlabor_income_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_nonfood_fuel_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_nonfood_vehicle_fuel_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_food_total_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_nonfood_total_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_total_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_transport_fuel_total_mo_real": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "job_earnings_individual_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "job_earnings_hh_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "hh_nonlabor_income_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_nonfood_fuel_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_food_total_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_nonfood_total_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_total_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "expenditure_transport_fuel_total_mo_real_usd": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Exploratory sidecar variables retain missingness after left joins.
        "n_symptoms": pa.Column(int, checks=pa.Check.ge(0), nullable=True, coerce=True),
        "many_symptoms": _binary_column(nullable=True),
        "recent_hospitalised": _binary_column(nullable=True),
        "recent_accident_2y": _binary_column(nullable=True),
        "recently_widowed_5y": _binary_column(nullable=True),
        "debt_q4": _binary_column(nullable=True),
        "high_med_oop": _binary_column(nullable=True),
        # Add IFLS4 indicators
        "urban_vehicle_hh_ifls4": _binary_column(nullable=True),
        "coal_worker_hh_ifls4": _binary_column(nullable=True),
        "coal_worker_individual_ifls4": _binary_column(nullable=True),
        "palm_farmer_hh_ifls4": _binary_column(nullable=True),
        "palm_farmer_individual_ifls4": _binary_column(nullable=True),
        "fuel_share_ifls4": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        "fuel_share_100_ifls4": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "transport_share_100_ifls4": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "fuel_transport_share_100_ifls4": pa.Column(
            float, checks=pa.Check.between(0, 100), nullable=True, coerce=True
        ),
        "fuel_share_z_ifls4": pa.Column(float, nullable=True, coerce=True),
        "fuel_transport_share_z_ifls4": pa.Column(float, nullable=True, coerce=True),
        "fuel_share_quartile_ifls4": pa.Column(
            float, checks=pa.Check.between(1, 4), nullable=True, coerce=True
        ),
        **{
            f"{col}_ifls4": _binary_column(nullable=True)
            for col in ["cash_transfer_recipient", *CASH_TRANSFER_CARD_COLUMNS]
        },
    },
    strict=True,
    unique=["pidlink", "wave"],
)
